### ISSUE TITLE
"could not parse package format" / "no matching crate found" in workspace containing 1 crate

### ISSUE THREAD

**Issue by antifuchs** [cargo-bins/release-pr#142]
I'm using the release-pr action to create a release PR on boinkor-net/governor, and in recent months it has started failing like in [this run](https://github.com/boinkor-net/governor/actions/runs/11411600835/job/31756153458):

```console
(huge amount of json from `cargo metadata`
2024-10-18T22:06:04.7551019Z ##[warning]could not parse package format: "path+file:///home/runner/work/governor/governor/governor#0.6.3", skipping
2024-10-18T22:06:04.7559605Z ##[error]no matching crate found
```

I'm not sure what to make of this, it seems that this is a reasonable package ID? I can't find that error string in the release-pr source code, and now I'm confused.

**Comment by NobodyXu** [comment]
From the [log](https://github.com/boinkor-net/governor/actions/runs/11411600835/job/31756153458#step:1:28):

```
Download action repository 'cargo-bins/release-pr@v2' (SHA:deeacca5a38bacc74a3f444b798f4b9bba40f6ad)
```

it seems that you're using an old release [v2.1.0](https://github.com/cargo-bins/release-pr/releases/tag/v2.1.0)
The issue should be fixed in [v2.1.3](https://github.com/cargo-bins/release-pr/releases/tag/v2.1.3).

I'm not sure why it isn't picking up latest release automatically... have to take another look

**Comment by NobodyXu** [comment]
Hmmm I don't know how to update the v2 tag and end up creating a new v2-new tag

**Comment by passcod** [comment]
you can force-push tags

**Comment by antifuchs** [comment]
Re-ran the workflow and this time it picked the right version. Thanks for debugging this so quickly, folks!
