### ISSUE TITLE
Meaning of "The action sets the following"

### ISSUE THREAD

**Issue by mmagician** [cargo-bins/release-pr#64]
What does this actually mean, where is it set?

I guess especially `version` would be useful - ideally once a PR is merged, another action is triggered to actually publish the crates with the version that was just merged.

Do you perhaps have a workflow example where you're also automating this action of publishing to crates.io, and if so could you share please?

**Comment by passcod** [comment]
These are action outputs: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs-for-docker-container-and-javascript-actions

**Comment by passcod** [comment]
I do not have any workflow publishing to crates.io, due to current security concerns (which will be resolved when [scoped tokens](https://github.com/rust-lang/rfcs/pull/2947) are implemented).

---

The motivation and precursor for this action are workflows that _tag_ a release when the PR is merged, which then trigger optimised and published builds. But there's no direct way at the moment to use the outputs of this action from the merge. This is planned, to facilitate writing such actions (the afore-mentioned tagging ones do some horrible string parsing on commit messages from a `push` event), but I haven't done the design yet of how to pass that data along in a reliable manner.

My current idea draft is to embed a little json payload in a comment in the body of the PR, like:

```
<!-- {"release-pr-v1":{"version":{"desired":"patch","actual":"1.2.3"},"crate":{...}}} -->
```

which the second action would then be able to find from the [`pull_request` close](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request) event, rather than working backward from the commit message. This would also eliminate the need to require a particular manner of merging this release PR.

---

In providing these outputs, this action is merely being a good citizen and providing derived values out the other end, rather than the user needing to parse/figure those out again. Examples of use could be to:
- create a notification in a slack channel,
- file an "intent to release",
- add labels to open PRs to prevent them from merging during the "release window"
